{
  "openapi": "3.0.0",
  "info": {
    "title": "WalletAPI",
    "description": "Created by [Ruslan Zahriadskyi](https://github.com/RuslanZahriadskyi)",
    "version": "1.0.0"
  },
  "consumens": ["application/json"],
  "produces": ["application/json"],
  "tags": [
    {
      "name": "operations",
      "description": "Operations with your wallet"
    },
    {
      "name": "user",
      "description": "Operations with user"
    }
  ],
  "servers": [
    { "url": "https://own-wallet.herokuapp.com/" },
    { "url": "http://localhost:3000" }
  ],
  "paths": {
    "/api/operations": {
      "get": {
        "tags": ["operations"],
        "summary": "Get All User Operations",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Success Response"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error 403"
                }
              }
            }
          },
          "500": {
            "description": "Iternal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error 500"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": ["operations"],
        "summary": "Create New Operations",
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "date",
                  "category",
                  "amount",
                  "type",
                  "balanceAfter",
                  "typeBalanceAfter"
                ],
                "properties": {
                  "date": {
                    "type": "number",
                    "example": 1633878419,
                    "description": "date"
                  },
                  "category": {
                    "type": "string",
                    "example": "sallary",
                    "description": "category"
                  },
                  "comments": {
                    "type": "string",
                    "example": "Sallary per month",
                    "description": "comments"
                  },
                  "amount": {
                    "type": "number",
                    "example": 10000,
                    "description": "amount"
                  },
                  "type": {
                    "type": "string",
                    "example": "income or outlay",
                    "description": "type"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "responses status",
                      "example": "success"
                    },
                    "code": {
                      "type": "string",
                      "description": "responses code",
                      "example": "200"
                    },
                    "data": {
                      "type": "object",
                      "description": "responses data",
                      "example": {
                        "newOperation": {
                          "date": 1620659219,
                          "type": "outlay",
                          "category": "house",
                          "comments": "test1",
                          "amount": 4000,
                          "balanceAfter": -5000
                        },
                        "totalBalance": 5000
                      }
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error 403"
                }
              }
            }
          },
          "500": {
            "description": "Iternal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error 500"
                }
              }
            }
          }
        }
      }
    },
    "/api/operations/statistics/{month}/{year}": {
      "get": {
        "tags": ["operations"],
        "summary": "Get statistic per month and year",
        "security": [{ "Bearer": [] }],
        "parameters": [
          {
            "name": "month",
            "in": "path",
            "description": "month request",
            "required": "true",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "year",
            "in": "path",
            "description": "year request",
            "required": "true",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "responses status",
                      "example": "success"
                    },
                    "code": {
                      "type": "string",
                      "description": "responses code",
                      "example": "200"
                    },
                    "statistic": {
                      "type": "object",
                      "description": "responses data",
                      "example": {
                        "monthStatistic": [
                          {
                            "_id": "kids",
                            "count": 2000
                          },
                          {
                            "_id": "regular",
                            "count": 5000
                          }
                        ],
                        "incomeAndOutlayAmount": [
                          {
                            "_id": "outlay",
                            "count": 2000
                          },
                          {
                            "_id": "income",
                            "count": 5000
                          }
                        ]
                      }
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error 403"
                }
              }
            }
          },
          "500": {
            "description": "Iternal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error 500"
                }
              }
            }
          }
        }
      }
    },
    "/api/users/registration": {
      "post": {
        "tags": ["user"],
        "summary": "Register new user",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["email", "password", "name"],
                "properties": {
                  "password": {
                    "type": "string",
                    "example": "some password",
                    "description": "Password"
                  },
                  "name": {
                    "type": "string",
                    "example": "some name",
                    "description": "Name"
                  },
                  "subscription": {
                    "type": "string",
                    "example": "some subscription",
                    "description": "Subscription"
                  },
                  "email": {
                    "type": "string",
                    "example": "some email",
                    "description": "Email"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "responses status",
                      "example": "success"
                    },
                    "code": {
                      "type": "string",
                      "description": "responses code",
                      "example": "201"
                    },
                    "data": {
                      "type": "object",
                      "description": "responses data",
                      "example": {
                        "id": "60d9f35e8a52085120891b18",
                        "email": "example@email.com",
                        "subscription": "pro",
                        "avatar": "https://path.to.user.avatar"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error 400"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error 403"
                }
              }
            }
          },
          "409": {
            "description": "Conflict",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "status",
                      "example": "error"
                    },
                    "code": {
                      "type": "string",
                      "description": "code",
                      "example": "409"
                    },
                    "message": {
                      "type": "string",
                      "description": "conflict",
                      "example": "This email already exist"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Iternal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error 500"
                }
              }
            }
          }
        }
      }
    },
    "/api/users/login": {
      "post": {
        "tags": ["user"],
        "summary": "Login user",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["email", "password"],
                "properties": {
                  "password": {
                    "type": "string",
                    "example": "some password",
                    "description": "Password"
                  },

                  "email": {
                    "type": "string",
                    "example": "some email",
                    "description": "Email"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Login user success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "responses status",
                      "example": "success"
                    },
                    "code": {
                      "type": "string",
                      "description": "responses code",
                      "example": "200"
                    },
                    "data": {
                      "type": "object",
                      "description": "responses data",
                      "example": {
                        "token": "User token after success login"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Invaid credincials",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "responses status",
                      "example": "error"
                    },
                    "code": {
                      "type": "string",
                      "description": "responses code",
                      "example": "401"
                    },
                    "message": {
                      "type": "string",
                      "description": "responses message",
                      "example": "Invalid creadentials"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error 400"
                }
              }
            }
          },
          "500": {
            "description": "Iternal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error 500"
                }
              }
            }
          }
        }
      }
    },
    "/api/users/current": {
      "get": {
        "tags": ["user"],
        "summary": "Get Current User",
        "security": [{ "Bearer": [] }],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User Response"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error 403"
                }
              }
            }
          },
          "500": {
            "description": "Iternal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error 500"
                }
              }
            }
          }
        }
      }
    },
    "/api/users/": {
      "post": {
        "tags": ["user"],
        "summary": "Change user subscription",
        "security": [{ "Bearer": [] }],
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["subscription"],
                "properties": {
                  "subscription": {
                    "type": "string",
                    "example": "starter or pro or business",
                    "description": "Subscription"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User Response"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error 400"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error 403"
                }
              }
            }
          },
          "500": {
            "description": "Iternal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error 500"
                }
              }
            }
          }
        }
      }
    },
    "/api/users/verify": {
      "post": {
        "tags": ["user"],
        "summary": "Repeatedly UserVerify",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["email"],
                "properties": {
                  "email": {
                    "type": "string",
                    "example": "email@example.com",
                    "description": "Email"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "responses status",
                      "example": "success"
                    },
                    "code": {
                      "type": "string",
                      "description": "responses code",
                      "example": "200"
                    },
                    "data": {
                      "type": "object",
                      "description": "responses data",
                      "example": { "message": "Resubmitted success!" }
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error 403"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error 404"
                }
              }
            }
          },
          "500": {
            "description": "Iternal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error 500"
                }
              }
            }
          }
        }
      }
    },
    "/api/users/logout": {
      "post": {
        "tags": ["user"],
        "summary": "Logout user",
        "security": [{ "Bearer": [] }],
        "parameters": [],
        "responses": {
          "204": { "description": "Success" },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error 403"
                }
              }
            }
          },
          "500": {
            "description": "Iternal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error 500"
                }
              }
            }
          }
        }
      }
    },
    "/api/users/avatars": {
      "patch": {
        "tags": ["user"],
        "summary": "Change user avatar",
        "security": [{ "Bearer": [] }],
        "parameters": [
          {
            "name": "avatar",
            "in": "formData",
            "description": "upload new avatar",
            "required": true,
            "schema": { "type": "file" }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "responses status",
                      "example": "success"
                    },
                    "code": {
                      "type": "string",
                      "description": "responses code",
                      "example": "200"
                    },
                    "avatarUrl": {
                      "type": "string",
                      "description": "responses url",
                      "example": "https://res.cloudinary.com/inferus/image/upload/v1624917610/avatars/r8in49olqwk0mxueazau.jpg"
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error 403"
                }
              }
            }
          },
          "500": {
            "description": "Iternal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error 500"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Success Response": {
        "description": "success",
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "description": "responses status",
            "example": "success"
          },
          "code": {
            "type": "string",
            "description": "responses code",
            "example": "200"
          },
          "data": {
            "type": "object",
            "description": "responses data",
            "example": {
              "userOperations": [],
              "totalBalance": 5000
            }
          }
        },
        "User Response": {
          "type": "object",
          "properties": {
            "status": {
              "type": "string",
              "description": "responses status",
              "example": "success"
            },
            "code": {
              "type": "string",
              "description": "responses code",
              "example": "200"
            },
            "data": {
              "type": "object",
              "description": "responses data",
              "example": {
                "user": {
                  "name": "One More",
                  "email": "user.email@mail.com",
                  "subscription": "pro"
                }
              }
            }
          }
        },
        "Error 400": {
          "description": "Bad Request",
          "type": "object",
          "properties": {
            "status": {
              "type": "string",
              "description": "responses status",
              "example": "error"
            },
            "code": {
              "type": "string",
              "description": "responses code",
              "example": "400"
            },
            "message": {
              "type": "string",
              "description": "responses message",
              "example": "Bad Request"
            }
          }
        },
        "Error 403": {
          "description": "Forbidden",
          "type": "object",
          "properties": {
            "status": {
              "type": "string",
              "description": "responses status",
              "example": "error"
            },
            "code": {
              "type": "string",
              "description": "responses code",
              "example": "403"
            },
            "message": {
              "type": "string",
              "description": "responses message",
              "example": "Forbidden"
            }
          }
        },
        "Error 404": {
          "description": "Not Found",
          "type": "object",
          "properties": {
            "status": {
              "type": "string",
              "description": "responses status",
              "example": "error"
            },
            "code": {
              "type": "string",
              "description": "responses code",
              "example": "404"
            },
            "message": {
              "type": "string",
              "description": "responses message",
              "example": "Not Found"
            }
          }
        },
        "Error 500": {
          "description": "Iternal Server Error",
          "type": "object",
          "properties": {
            "status": {
              "type": "string",
              "description": "responses status",
              "example": "fail"
            },
            "code": {
              "type": "string",
              "description": "responses code",
              "example": "500"
            },
            "message": {
              "type": "string",
              "description": "responses message",
              "example": "User password is required"
            },
            "data": {
              "type": "string",
              "description": "responses data",
              "example": "Internal Server Found"
            }
          }
        }
      },
      "User Response": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "description": "responses status",
            "example": "success"
          },
          "code": {
            "type": "string",
            "description": "responses code",
            "example": "200"
          },
          "data": {
            "type": "object",
            "description": "responses data",
            "example": {
              "user": {
                "name": "One More",
                "email": "user.email@mail.com",
                "subscription": "pro"
              }
            }
          }
        }
      },
      "Error 400": {
        "description": "Bad Request",
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "description": "responses status",
            "example": "error"
          },
          "code": {
            "type": "string",
            "description": "responses code",
            "example": "400"
          },
          "message": {
            "type": "string",
            "description": "responses message",
            "example": "Bad Request"
          }
        }
      },
      "Error 403": {
        "description": "Forbidden",
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "description": "responses status",
            "example": "error"
          },
          "code": {
            "type": "string",
            "description": "responses code",
            "example": "403"
          },
          "message": {
            "type": "string",
            "description": "responses message",
            "example": "Forbidden"
          }
        }
      },
      "Error 404": {
        "description": "Not Found",
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "description": "responses status",
            "example": "error"
          },
          "code": {
            "type": "string",
            "description": "responses code",
            "example": "404"
          },
          "message": {
            "type": "string",
            "description": "responses message",
            "example": "Not Found"
          }
        }
      },
      "Error 500": {
        "description": "Iternal Server Error",
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "description": "responses status",
            "example": "fail"
          },
          "code": {
            "type": "string",
            "description": "responses code",
            "example": "500"
          },
          "message": {
            "type": "string",
            "description": "responses message",
            "example": "User password is required"
          },
          "data": {
            "type": "string",
            "description": "responses data",
            "example": "Internal Server Found"
          }
        }
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "schemes": ["http", "https"]
}
